# Generated by Django 4.1 on 2023-04-26 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="lesson_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="onlinecourse.course"
            ),
        ),
    ]
