# Generated by Django 4.1 on 2023-04-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0002_alter_question_lesson_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="question_id",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="lesson_id",
            new_name="courses",
        ),
    ]
