# Generated by Django 4.1 on 2023-04-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0003_rename_question_id_choice_question_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="courses",
            new_name="course",
        ),
    ]
