# Generated by Django 4.1 on 2023-04-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0004_rename_courses_question_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="is_corret",
            new_name="is_correct",
        ),
    ]
